#if defined _knifemodels_const_included
    #endinput
#endif 

#define _knifemodels_const_included

/** 
 * Default knife models
 */
#define KM_MODEL_V_DEFAULT "models/v_knife.mdl"
#define KM_MODEL_P_DEFAULT "models/p_knife.mdl"

/** 
 * Default knife sounds
 */
#define KM_SOUND_DEPLOY1    "weapons/knife_deploy1.wav"
#define KM_SOUND_HIT1       "weapons/knife_hit1.wav"
#define KM_SOUND_HIT2       "weapons/knife_hit2.wav"
#define KM_SOUND_HIT3       "weapons/knife_hit3.wav"
#define KM_SOUND_HIT4       "weapons/knife_hit4.wav"
#define KM_SOUND_HITWALL1   "weapons/knife_hitwall1.wav"
#define KM_SOUND_SLASH1     "weapons/knife_slash1.wav"
#define KM_SOUND_SLASH2     "weapons/knife_slash2.wav"
#define KM_SOUND_STAB       "weapons/knife_stab.wav"

/** 
 * Maximum buffer length for knife models
 */
#define KM_MAX_MODEL_LENGTH        128

/** 
 * Maximum buffer length for knife sounds
 */
#define KM_MAX_SOUND_LENGTH        128

/**
 * Maximum buffer length for knife messages
 */
#define KM_MAX_MESSAGE_LENGTH      128

/** 
 * Maximum buffer length for knife attributes
 */
#define KM_MAX_ATTRIBUTE_LENGTH    64